### ISSUE TITLE
-x option is not parsed?

### ISSUE THREAD

**Issue by mailinglists35** [jbd/msrsync#12]
````
[root@gw2 sbin]# msrsync -p 10 -f 100 -s 32M -P -d --stats -r "-axPHAX --inplace --numeric-ids --exclude=*\.cache*" / /srv/gw2/os-backup/
[106906/106906 entries] [128.0 T/128.0 T transferred] [18738 entries/s] [22.4 T/s bw] [monq 0] [jq 0]Uncaught exception:
Traceback (most recent call last):
  File "/usr/local/sbin/msrsync", line 1093, in msrsync
    for bucket_files_nr, bucket_size, bucket in buckets(src, options.files, options.s):
  File "/usr/local/sbin/msrsync", line 563, in buckets
    for fsize, rpath in crawl(path, relative=True):
  File "/usr/local/sbin/msrsync", line 539, in crawl
    size = os.lstat(fullpath).st_size
OSError: [Errno 2] No such file or directory: '/proc/10809/task/10809/fd/3'

Process Process-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 869, in rsync_monitor_worker
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
    for result in consume_queue(monitor_queue):
  File "/usr/local/sbin/msrsync", line 674, in consume_queue
    item = jobs_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

Process Process-13:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 942, in messages_worker
    for result in consume_queue(G_MESSAGES_QUEUE):
  File "/usr/local/sbin/msrsync", line 674, in consume_queue
    item = jobs_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
````

/proc should not be there.

**Comment by mailinglists35** [comment]
I've manually excluded /proc, still crash:

````
[root@gw2 sbin]# msrsync -p 10  -P -d --stats -r "-axPHAX --inplace --numeric-ids --exclude=*\.cache* --exclude=/proc --exclude=/sys --exclude=/dev" / /srv/gw2/os-backup/
[193006/193006 entries] [128.0 T/128.0 T transferred] [26552 entries/s] [17.6 T/s bw] [monq 1] [jq 0]Uncaught exception:
Traceback (most recent call last):
  File "/usr/local/sbin/msrsync", line 1093, in msrsync
    for bucket_files_nr, bucket_size, bucket in buckets(src, options.files, options.s):
  File "/usr/local/sbin/msrsync", line 563, in buckets
    for fsize, rpath in crawl(path, relative=True):
  File "/usr/local/sbin/msrsync", line 539, in crawl
    size = os.lstat(fullpath).st_size
OSError: [Errno 2] No such file or directory: '/proc/23138/task/23138/fd/3'

Process Process-8:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
Process Process-12:
Process Process-9:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/local/sbin/msrsync", line 869, in rsync_monitor_worker
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    for result in consume_queue(monitor_queue):
  File "/usr/local/sbin/msrsync", line 674, in consume_queue
    item = jobs_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

Process Process-13:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 942, in messages_worker
    for result in consume_queue(G_MESSAGES_QUEUE):
  File "/usr/local/sbin/msrsync", line 674, in consume_queue
    item = jobs_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
````

**Comment by mailinglists35** [comment]
also exclude proc/** crashes

````
[root@gw2 sbin]# msrsync -p 10  -P -d --stats -r "-axPHAX --inplace --numeric-ids --exclude=*\.cache* --exclude=proc/** --exclude=sys/** --exclude=dev/**" / /srv/gw2/os-backup/
[69006/69006 entries] [128.0 T/128.0 T transferred] [25658 entries/s] [47.6 T/s bw] [monq 0] [jq 0]Uncaught exception:
Traceback (most recent call last):
  File "/usr/local/sbin/msrsync", line 1093, in msrsync
    for bucket_files_nr, bucket_size, bucket in buckets(src, options.files, options.s):
  File "/usr/local/sbin/msrsync", line 563, in buckets
    for fsize, rpath in crawl(path, relative=True):
  File "/usr/local/sbin/msrsync", line 539, in crawl
    size = os.lstat(fullpath).st_size
OSError: [Errno 2] No such file or directory: '/proc/4043/task/4043/fd/3'

Process Process-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

Process Process-13:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 942, in messages_worker
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 869, in rsync_monitor_worker
    for result in consume_queue(G_MESSAGES_QUEUE):
  File "/usr/local/sbin/msrsync", line 674, in consume_queue
    item = jobs_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    for result in consume_queue(monitor_queue):
  File "/usr/local/sbin/msrsync", line 674, in consume_queue
    item = jobs_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    kind, result = conn.recv()
EOFError
Process Process-8:
Traceback (most recent call last):
Process Process-3:
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-2:
Process Process-7:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
IOError: [Errno 32] Broken pipe
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/sbin/msrsync", line 831, in rsync_worker
    jobs_queue.put(StopIteration)
  File "<string>", line 2, in put
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
````

**Comment by mailinglists35** [comment]
#7 related but not the same

**Comment by mailinglists35** [comment]
oh, thanks for the explanation. I can live with that if that is the workaround.

but this means that -x (exclude other filesystems) does not work and I must use the exclude trick?

**Comment by jbd** [comment]
I don't think the `-x` rsync is working with the `--files-from` option.

It makes me think that the choice of `-x` for my msrsync option is not very smart. I'll change it to prevent the confusion with the `-x/--one-file-system` from rsync. 

Adding a "don't cross filesystem" option at msrsync level similar to rsync's would be a nice to have feature. I don't want to duplicate too much feature between msrsync and rsync, but this one makes sense. I'll add that to my TODO list. 

If this feel clumsy to you, I'll urge you to look at the other tools I mentioned in the project README =) I don't have a look of time to work on msrsync at the moment.
